apiVersion: v1
kind: Pod
metadata:
  name: opencapi-privileged-sys-devices-ocxl-pod
  labels:
    name: opencapi-privileged-sys-devices-ocxl
  namespace: fabriceproject
  annotations:
    openshift.io/scc: privileged
spec:
  nodeName: hawk07.ocp4.ocpcapi.com
  containers:
    - name: opencapi-privileged-sys-devices-ocxl-pod
      image: docker.io/fmoyen/capiapp:latest
      ports:
        - containerPort: 80
          name: www
      volumeMounts:
        - name: sys-devices-ocxl
          mountPath: /OCXLSysDevice
      securityContext:
        privileged: true
  serviceAccount: fabriceproject-service-account
  serviceAccountName: fabriceproject-service-account

  volumes:
    - name: sys-devices-ocxl
      persistentVolumeClaim:
        claimName: sys-devices-ocxl-pvc

