kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: images-ad9h3-pvc
  namespace: fabriceproject
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem 
  resources:
    requests:
      storage: 500Mi 
  storageClassName: images-ad9h3-storageclass
