kind: Deployment
apiVersion: apps/v1
metadata:
  name: oc-ad9h7-pr-novol
  namespace: fabriceproject
  labels:
    app: oc-ad9h7
    app.kubernetes.io/component: oc-ad9h7
    app.kubernetes.io/instance: oc-ad9h7
    app.kubernetes.io/part-of: capiapp-app
    app.openshift.io/runtime-namespace: fabriceproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oc-ad9h7
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: oc-ad9h7
        deploymentconfig: oc-ad9h7
    spec:
      containers:
        - name: oc-ad9h7-pod
          image: docker.io/fmoyen/capiapp:latest
          resources:
            limits:
              xilinx.com/fpga-ad9h7_ocapi-0x0666: 1 # requesting 1x AD9H7 opencapi
          volumeMounts:
            - name: images-ad9h7
              mountPath: /images/ad9h7
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      volumes:
        - name: images-ad9h7
          persistentVolumeClaim:
            claimName: images-ad9h7-pvc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

