kind: Deployment
apiVersion: apps/v1
metadata:
  name: oc-ad9h3-anyuid
  namespace: fabriceproject
  labels:
    app: oc-ad9h3
    app.kubernetes.io/component: oc-ad9h3
    app.kubernetes.io/instance: oc-ad9h3
    app.kubernetes.io/part-of: capiapp-app
    app.openshift.io/runtime-namespace: fabriceproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oc-ad9h3
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: oc-ad9h3
        deploymentconfig: oc-ad9h3
    spec:
      containers:
        - name: oc-ad9h3-pod
          image: docker.io/fmoyen/capiapp:latest
          resources:
            limits:
              xilinx.com/fpga-ad9h3_ocapi-0x0667: 1 # requesting 1x AD9H7 opencapi
          volumeMounts:
            - name: sys-devices-ocxl0-ad9h3
              mountPath: /OCXLSys/devices/pci0004:00/0004:00:00.0
            - name: sys-bus-ocxl0-ad9h3
              mountPath: /OCXLSys/bus/pci/devices/0004:00:00.0
            - name: sys-devices-ocxl1-ad9h3
              mountPath: /OCXLSys/devices/pci0004:00/0004:00:00.1
            - name: sys-bus-ocxl1-ad9h3
              mountPath: /OCXLSys/bus/pci/devices/0004:00:00.1
            - name: sys-bus-slots-jp90nvt1
              mountPath: /OCXLSys/bus/pci/slots/JP90NVT1
            - name: lib-modules-ocxl
              mountPath: /lib/modules
            - name: images-ad9h3
              mountPath: /images/ad9h3
          securityContext:
            anyuid: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      volumes:
        - name: sys-devices-ocxl0-ad9h3
          persistentVolumeClaim:
            claimName: sys-devices-ocxl.0-ad9h3-pvc
        - name: sys-bus-ocxl0-ad9h3
          persistentVolumeClaim:
            claimName: sys-bus-ocxl.0-ad9h3-pvc
        - name: sys-devices-ocxl1-ad9h3
          persistentVolumeClaim:
            claimName: sys-devices-ocxl.1-ad9h3-pvc
        - name: sys-bus-ocxl1-ad9h3
          persistentVolumeClaim:
            claimName: sys-bus-ocxl.1-ad9h3-pvc
        - name: sys-bus-slots-jp90nvt1
          persistentVolumeClaim:
            claimName: sys-bus-slots-jp90nvt1-pvc
        - name: lib-modules-ocxl
          persistentVolumeClaim:
            claimName: lib-modules-ocxl-pvc
        - name: images-ad9h3
          persistentVolumeClaim:
            claimName: images-ad9h3-pvc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

