kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sys-bus-slots-jp90nvt1-pvc
  namespace: fabriceproject
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem 
  resources:
    requests:
      storage: 1Gi 
  storageClassName: sys-bus-slots-jp90nvt1-storageclass 
