kind: Deployment
apiVersion: apps/v1
metadata:
  name: oc-privileged
  namespace: fabriceproject
  labels:
    app: oc-privileged
    app.kubernetes.io/component: oc-privileged
    app.kubernetes.io/instance: oc-privileged
    app.kubernetes.io/part-of: capiapp-app
    app.openshift.io/runtime-namespace: fabriceproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oc-privileged
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: oc-privileged
        deploymentconfig: oc-privileged
    spec:
      nodeName: hawk08.ocp4.ocpcapi.10.3.76.170.nip.io
      containers:
        - name: oc-privileged-pod
          image: docker.io/fmoyen/capiapp:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: sys-ocxl
              mountPath: /OCXLSys
            - name: lib-modules-ocxl
              mountPath: /lib/modules
            - name: images-ad9h3
              mountPath: /images/ad9h3
          securityContext:
            privileged: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      serviceAccount: fabriceproject-service-account
      serviceAccountName: fabriceproject-service-account
      volumes:
        - name: sys-ocxl
          persistentVolumeClaim:
            claimName: sys-ocxl-pvc
        - name: lib-modules-ocxl
          persistentVolumeClaim:
            claimName: lib-modules-ocxl-pvc
        - name: images-ad9h3
          persistentVolumeClaim:
            claimName: images-ad9h3-pvc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

