kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sys-devices-ocxl-ad9h7-pvc
  namespace: fabriceproject
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem 
  resources:
    requests:
      storage: 1Gi 
  storageClassName: sys-devices-ocxl-ad9h7-storageclass 
