kind: Deployment
apiVersion: apps/v1
metadata:
  name: capi-privileged
  namespace: fabriceproject
  labels:
    app: capi-privileged
    app.kubernetes.io/component: capi-privileged
    app.kubernetes.io/instance: capi-privileged
    app.kubernetes.io/part-of: capi-privileged-app
    app.openshift.io/runtime-namespace: fabriceproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capi-privileged
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: capi-privileged
        deploymentconfig: capi-privileged
    spec:
      containers:
        - name: capi-privileged
          image: docker.io/fmoyen/capiapp:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          securityContext:
            privileged: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      serviceAccount: fabriceproject-service-account
      serviceAccountName: fabriceproject-service-account
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
