apiVersion: v1
kind: PersistentVolume
metadata:
  name: images-ad9h3
  annotation:
    volume.beta.kubernetes.io/mount-options: ro
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: images-ad9h3-storageclass
  nfs:
    path: /export/Images/ad9h3
    server: 10.3.76.170
