kind: Deployment
apiVersion: apps/v1
metadata:
  name: capi-device-requested
  namespace: fabriceproject
  labels:
    app: capi-device-requested
    app.kubernetes.io/component: capi-device-requested
    app.kubernetes.io/instance: capi-device-requested
    app.kubernetes.io/part-of: capi-device-requested-app
    app.openshift.io/runtime-namespace: fabriceproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capi-device-requested
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: capi-device-requested
        deploymentconfig: capi-device-requested
    spec:
      containers:
        - name: capi-device-requested
          image: docker.io/fmoyen/capiapp:latest
          resources:
            limits:
              xilinx.com/fpga-u200_capi2-0x0665: 1 # requesting 1x U200 capi2
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
