apiVersion: v1
kind: Pod
metadata:
  name: capi-u200-pod
  labels:
    name: capi-u200
  namespace: fabriceproject
spec:
  containers:
  - name: capi-u200-pod
    image: docker.io/fmoyen/capiapp:latest
    resources:
      limits:
        xilinx.com/fpga-u200_capi2-0x0665: 1 # requesting 1x U200 capi2

